name: Deploy to EC2

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$EC2_SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem $EC2_USERNAME@$EC2_HOST <<EOF
          cd Blogging-Platform
          git pull origin dev
          npm install
          pm2 restart 0
        EOF
